"""Build a single-file PolliPi API server artifact.

The generated script embeds the local ``visit_monitor_server`` package and
installs a tiny import hook. Third-party dependencies remain external, matching
the Raspberry Pi deployment model where packages such as FastAPI, uvicorn,
Picamera2, and OpenCV come from the system or virtual environment.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


PACKAGE_NAME = "visit_monitor_server"
BUILD_INFO_MODULE = f"{PACKAGE_NAME}.build_info"


def _package_root() -> Path:
    return Path(__file__).resolve().parents[1]


def collect_sources(package_root: Path) -> dict[str, str]:
    """Return ``{module_name: source}`` for every Python file in the package."""
    sources: dict[str, str] = {}
    for path in sorted(package_root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        relative = path.relative_to(package_root)
        if relative.name == "__pycache__":
            continue
        if relative.name == "__init__.py":
            module_parts = (PACKAGE_NAME, *relative.parent.parts)
        else:
            module_parts = (PACKAGE_NAME, *relative.with_suffix("").parts)
        module_name = ".".join(part for part in module_parts if part)
        sources[module_name] = path.read_text(encoding="utf-8")
    return sources


def _git_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=Path(__file__).resolve().parents[4],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return ""


def _git_timestamp() -> str:
    try:
        return subprocess.check_output(
            ["git", "show", "-s", "--format=%cI", "HEAD"],
            cwd=Path(__file__).resolve().parents[4],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return ""


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _web_build_id(commit: str, timestamp: str) -> str:
    if not commit or commit == "unknown" or not timestamp:
        return ""
    cleaned = timestamp.replace("-", "").replace(":", "").replace("T", "-").replace("Z", "")
    if "+" in cleaned:
        cleaned = cleaned.split("+", 1)[0]
    return f"{commit}-{cleaned}"


def _web_build_metadata() -> dict[str, str]:
    for path in (
        _repo_root() / "packages" / "web" / "dist" / "build-info.json",
        _repo_root() / "packages" / "web" / "public" / "build-info.json",
    ):
        if not path.is_file():
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        return {
            "web_build_id": str(payload.get("web_build_id", "")).strip(),
            "git_commit": str(payload.get("git_commit", "")).strip(),
            "build_timestamp": str(payload.get("build_timestamp", "")).strip(),
        }
    return {}


def apply_build_metadata(
    sources: dict[str, str],
    *,
    git_commit: str,
    build_timestamp: str,
    web_build_id: str,
) -> dict[str, str]:
    """Embed metadata constants in the bundled build_info module."""
    patched = dict(sources)
    source = patched.get(BUILD_INFO_MODULE)
    if source is None:
        return patched
    replacements = {
        'EMBEDDED_GIT_COMMIT = ""': f'EMBEDDED_GIT_COMMIT = "{git_commit}"',
        'EMBEDDED_BUILD_TIMESTAMP = ""': f'EMBEDDED_BUILD_TIMESTAMP = "{build_timestamp}"',
        'EMBEDDED_DEPLOYMENT_MODE = ""': 'EMBEDDED_DEPLOYMENT_MODE = "packaged_artifact"',
        'EMBEDDED_WEB_BUILD_ID = ""': f'EMBEDDED_WEB_BUILD_ID = "{web_build_id}"',
    }
    for old, new in replacements.items():
        source = source.replace(old, new)
    patched[BUILD_INFO_MODULE] = source
    return patched


def render_bundle(sources: dict[str, str]) -> str:
    """Render the Python source for the deployable single-file artifact."""
    package_names = {PACKAGE_NAME}
    for name in sources:
        parts = name.split(".")
        for index in range(1, len(parts)):
            package_names.add(".".join(parts[:index]))
    package_json = json.dumps(sorted(package_names), ensure_ascii=True, indent=2)
    source_json = json.dumps(sources, ensure_ascii=True, indent=2)
    return f'''#!/usr/bin/env python3
"""Single-file PolliPi API server.

Generated by ``python -m visit_monitor_server.distribution.bundle_single_file``.
Do not edit by hand; change ``packages/server`` and rebuild this artifact.
"""
from __future__ import annotations

import argparse
import importlib.abc
import importlib.machinery
import sys


_POLLIPI_PACKAGES = set({package_json})
_POLLIPI_SOURCES = {source_json}


class _PolliPiBundleLoader(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, fullname, path=None, target=None):
        if fullname not in _POLLIPI_SOURCES:
            return None
        return importlib.machinery.ModuleSpec(
            fullname,
            self,
            is_package=fullname in _POLLIPI_PACKAGES,
        )

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        source = _POLLIPI_SOURCES[module.__name__]
        module.__file__ = f"<pollipi-bundle>/{{module.__name__.replace('.', '/')}}.py"
        if module.__name__ in _POLLIPI_PACKAGES:
            module.__path__ = [f"<pollipi-bundle>/{{module.__name__.replace('.', '/')}}"]
            module.__package__ = module.__name__
        else:
            module.__package__ = module.__name__.rpartition(".")[0]
        exec(compile(source, module.__file__, "exec"), module.__dict__)


sys.meta_path.insert(0, _PolliPiBundleLoader())

from visit_monitor_server.app import create_app  # noqa: E402

app = create_app()


def main() -> None:
    import uvicorn

    parser = argparse.ArgumentParser(description="Run the PolliPi API server.")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--log-level", default="info")
    args = parser.parse_args()
    uvicorn.run(app, host=args.host, port=args.port, log_level=args.log_level)


if __name__ == "__main__":
    main()
'''


def build(
    output: Path,
    package_root: Path | None = None,
    *,
    git_commit: str | None = None,
    build_timestamp: str | None = None,
    web_build_id: str = "",
) -> Path:
    """Write the bundled artifact to *output* and return its path."""
    root = package_root or _package_root()
    web_metadata = _web_build_metadata()
    metadata_commit = git_commit if git_commit is not None else web_metadata.get("git_commit") or _git_commit()
    metadata_timestamp = (
        build_timestamp
        or web_metadata.get("build_timestamp")
        or _git_timestamp()
        or datetime.now(timezone.utc).isoformat(timespec="seconds")
    )
    metadata_web_build_id = web_build_id or web_metadata.get("web_build_id", "") or _web_build_id(
        metadata_commit,
        metadata_timestamp,
    )
    sources = apply_build_metadata(
        collect_sources(root),
        git_commit=metadata_commit,
        build_timestamp=metadata_timestamp,
        web_build_id=metadata_web_build_id,
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_bundle(sources), encoding="utf-8")
    output.chmod(0o755)
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description="Bundle PolliPi into one Python script.")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--git-commit", default=None)
    parser.add_argument("--build-timestamp", default=None)
    parser.add_argument("--web-build-id", default="")
    args = parser.parse_args()
    path = build(
        args.output,
        git_commit=args.git_commit,
        build_timestamp=args.build_timestamp,
        web_build_id=args.web_build_id,
    )
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
