"""Build a single-file PolliPi API server artifact.

The generated script embeds the local ``visit_monitor_server`` package and
installs a tiny import hook. Third-party dependencies remain external, matching
the Raspberry Pi deployment model where packages such as FastAPI, uvicorn,
Picamera2, and OpenCV come from the system or virtual environment.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


PACKAGE_NAME = "visit_monitor_server"


def _package_root() -> Path:
    return Path(__file__).resolve().parents[1]


def collect_sources(package_root: Path) -> dict[str, str]:
    """Return ``{module_name: source}`` for every Python file in the package."""
    sources: dict[str, str] = {}
    for path in sorted(package_root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        relative = path.relative_to(package_root)
        if relative.name == "__pycache__":
            continue
        if relative.name == "__init__.py":
            module_parts = (PACKAGE_NAME, *relative.parent.parts)
        else:
            module_parts = (PACKAGE_NAME, *relative.with_suffix("").parts)
        module_name = ".".join(part for part in module_parts if part)
        sources[module_name] = path.read_text(encoding="utf-8")
    return sources


def render_bundle(sources: dict[str, str]) -> str:
    """Render the Python source for the deployable single-file artifact."""
    package_names = {PACKAGE_NAME}
    for name in sources:
        parts = name.split(".")
        for index in range(1, len(parts)):
            package_names.add(".".join(parts[:index]))
    package_json = json.dumps(sorted(package_names), ensure_ascii=True, indent=2)
    source_json = json.dumps(sources, ensure_ascii=True, indent=2)
    return f'''#!/usr/bin/env python3
"""Single-file PolliPi API server.

Generated by ``python -m visit_monitor_server.distribution.bundle_single_file``.
Do not edit by hand; change ``packages/server`` and rebuild this artifact.
"""
from __future__ import annotations

import argparse
import importlib.abc
import importlib.machinery
import sys


_POLLIPI_PACKAGES = set({package_json})
_POLLIPI_SOURCES = {source_json}


class _PolliPiBundleLoader(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, fullname, path=None, target=None):
        if fullname not in _POLLIPI_SOURCES:
            return None
        return importlib.machinery.ModuleSpec(
            fullname,
            self,
            is_package=fullname in _POLLIPI_PACKAGES,
        )

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        source = _POLLIPI_SOURCES[module.__name__]
        module.__file__ = f"<pollipi-bundle>/{{module.__name__.replace('.', '/')}}.py"
        if module.__name__ in _POLLIPI_PACKAGES:
            module.__path__ = [f"<pollipi-bundle>/{{module.__name__.replace('.', '/')}}"]
            module.__package__ = module.__name__
        else:
            module.__package__ = module.__name__.rpartition(".")[0]
        exec(compile(source, module.__file__, "exec"), module.__dict__)


sys.meta_path.insert(0, _PolliPiBundleLoader())

from visit_monitor_server.app import create_app  # noqa: E402

app = create_app()


def main() -> None:
    import uvicorn

    parser = argparse.ArgumentParser(description="Run the PolliPi API server.")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--log-level", default="info")
    args = parser.parse_args()
    uvicorn.run(app, host=args.host, port=args.port, log_level=args.log_level)


if __name__ == "__main__":
    main()
'''


def build(output: Path, package_root: Path | None = None) -> Path:
    """Write the bundled artifact to *output* and return its path."""
    root = package_root or _package_root()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_bundle(collect_sources(root)), encoding="utf-8")
    output.chmod(0o755)
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description="Bundle PolliPi into one Python script.")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    path = build(args.output)
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
